import "@/styles/globals.css";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { TRPCReactProvider } from "@/trpc/react";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <header>
            <nav>
              <ul className="flex space-x-4 p-4 bg-gray-800 text-white">
                <li>
                  <Link href="/">Home</Link>
                </li>
                <li>
                  <Link href="/pedidos/criar">Criar Pedido</Link>
                </li>
                <li>
                  <Link href="/pedidos">Pedidos</Link>
                </li>
              </ul>
            </nav>
          </header>
          <main>{children}</main>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
